version: 2
jobs:
  build:
    executor: machine
    environment:
      TL_IMAGE: macnica-image:0.7
    steps:
      - checkout
      - run:
          name: build
          command: docker build -t $TL_IMAGE .
      - run:
          name: get twistcli
          command: |
            curl -k -u $tl_u:$tl_p --output twistcli $TL_URL"/api/v1/util/twistcli"
            chmod +x twistcli
      - run:
          name: scan image
          command: |
            ./twistcli images scan --details --address $TL_URL -u $tl_u -p $tl_p --ci $TL_C $TL_IMAGE

