version: 2
jobs:
  build:
    executor: machine
    environment:
      TL_IMAGE: "macnicadevops/cci-demo"
    steps:
      - checkout
      - run:
          name: build
          command: docker build -t $TL_IMAGE":"$CIRCLE_BUILD_NUM .
      - run:
          name: get twistcli
          command: |
            curl -k -u $tl_u:$tl_p --output twistcli $TL_URL"/api/v1/util/twistcli"
            chmod +x twistcli
      - run:
          name: scan image
          command: |
            ./twistcli images scan --details --address $TL_URL -u $tl_u -p $tl_p --ci $TL_IMAGE":"$CIRCLE_BUILD_NUM | tee result.out
            e=`cat result.out | grep -c "threshold check results: PASS"`
            if [ $e -eq 2 ]; then
              echo "Build Scan succeeded"
              exit 0
            else
              echo "Build failed"
              exit 1
            fi
